#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate translation/target/msg1_translated.csv from translation/source/msg1_strings.csv.

- Cleans 1~4 char binary-noise prefixes from `source` (validated: cleaned text must be
  a suffix of the raw source).
- Translates to Traditional Chinese, preserving printf placeholders and ASCII quotes.
- Keeps embedded game control codes (B1 / C7 / C%d) untouched.
- Output: utf-8-sig, QUOTE_ALL, escapechar='\\', CRLF (same as input).
"""
import csv, re, sys

SRC = "translation/source/msg1_strings.csv"
DST = "translation/target/msg1_translated.csv"

# num -> (cleaned_source, target, note)
M = {
0:("Fleet Commander Tamon Yamaguchi delivered his","艦隊司令山口多聞在",""),
1:("final order to his crew on the flight deck of","重創的飛龍號飛行甲板上，",""),
2:("the severely damaged Hiryu.","向全體乘員下達了最後的命令。",""),
3:("I have never seen more courageous soldiers than","我從未見過比","移除開頭雜訊「J」"),
4:("the men of the Hiryu. However, her time is up","飛龍號官兵更英勇的戰士。然而，她的時限已到，",""),
5:("and you must all return home to your families.","各位都該回到家人身邊了。",""),
6:("Commander, as her captain, I will take care of","司令官，身為艦長，我會",""),
7:("her to the very end. The Navy needs you! Please,","陪她到最後一刻。海軍需要您！請",""),
8:("let her go and see the crew safely home.","您放手讓她走，帶乘員平安回家。",""),
9:("Ever since I boarded the Hiryu, I have wished to","自從登上飛龍號那天起，我就盼望","移除開頭雜訊「sV」"),
10:("die with her. Today, we are like one. Would you","能與她共存亡。今天，我們已合為一體。您",""),
11:("be so cruel to tear apart a single soul?","忍心將一個靈魂生生拆散嗎？",""),
12:("Look, it's a beautiful moon tonight. We're on","看，今晚的月色真美。我們在海上","移除開頭雜訊「(M」"),
13:("the sea for months at a time, but you know what?","一待就是好幾個月，但你知道嗎？",""),
14:("I've never paused to enjoy a peaceful moment on","我從未停下來，在這艘優雅的船上",""),
15:("board this graceful ship.","享受片刻的寧靜。",""),
16:("Commander...","司令官……",""),
17:("The moon cast a gentle ray of light upon the","月光溫柔地灑在",""),
18:("sinking deck, and the two officers shared the","下沉的甲板上，兩位軍官帶著",""),
19:("Hiryu's final moments with peaceful smiles on","安詳的微笑，迎接飛龍號的",""),
20:("their faces.","最後時刻。",""),
21:("The true battle has yet to come. I promise to","真正的戰鬥還在後頭。我發誓","移除開頭雜訊「PU'1」（4 字元，較罕見）"),
22:("return to the Philippines and defeat the","必將重返菲律賓，",""),
23:("Japanese once and for all!","徹底擊敗日本！",""),
24:("I shall return!","我必將歸來！","移除開頭雜訊「E」；麥克阿瑟名言"),
25:("Welcome to \"The Voice of Freedom\". This is","歡迎收聽\"自由之聲\"。我是","移除開頭雜訊「{」；保留 ASCII 引號"),
26:("General MacArthur speaking. My friends in the","麥克阿瑟將軍。菲律賓的",""),
27:("Philippines, I am finally back!","朋友們，我終於回來了！",""),
28:("I have returned!","我回來了！",""),
29:("--Intelligence Report-- It appears that leaders of the Allied forces have convened in a meeting.","--情報報告-- 盟軍各國領袖似乎召開了一場會議。","開頭的「I」判定為雜訊（「--」才是原文起頭），不確定，待複核"),
30:("On %s %d, %d, the leaders of the United","%s月%d日，%d年，美國、","%s 為英文月份字串，顯示會是「February月…」形式，待複核"),
31:("States, England, and the U.S.S.R. met at Yalta in","英國與蘇聯的領袖在克里米亞的",""),
32:("the Crimea. This meeting of the \"Big Three\" later","雅爾達會面。這場\"三巨頭\"會議",""),
33:("became known as the famous Yalta Conference.","後來成為著名的雅爾達會議。",""),
34:("We all know Germany is finished. After Germany","我們都知道德國完了。德國",""),
35:("falls, we will wait two to three months before","投降後，我們將等兩三個月",""),
36:("joining the war.","再參戰。",""),
37:("That is good news for all of us Allies. The","這對盟軍全體都是好消息。蘇聯",""),
38:("strength of U.S.S.R. will be invaluable in the","的戰力在太平洋戰場",""),
39:("Pacific.","將是無價之寶。",""),
40:("As for Germany, we will ask for their surrender,","至於德國，我們將要求其投降，",""),
41:("which is long overdue, within the next two or","這早就該做了，就在未來兩三",""),
42:("three days.","天內。",""),
43:("I have no objections. Once the Germans","我沒有異議。一旦德國",""),
44:("surrender, we must focus our energies on","投降，我們必須全力",""),
45:("rebuilding a peaceful Europe.","重建和平的歐洲。",""),
46:("There are still many issues that we must","仍有許多議題需要",""),
47:("discuss, but, we are all busy, so we'll leave","討論，但大家事務繁忙，",""),
48:("them for another time.","就留待下次吧。",""),
49:("Well then, this meeting is officially over. May","那麼，本次會議正式結束。願","移除開頭雜訊「q~aRt」"),
50:("the skies be brighter when next we meet.","下次相見時，天空更加明朗。",""),
51:("Let's hope this ugly war ends soon.","但願這場醜惡的戰爭早日結束。",""),
52:("My sentiments exactly.","我完全同意。",""),
53:("On %s %d, %d, the U.S.S.R. has formally","%s月%d日，%d年，蘇聯正式","移除開頭雜訊「v」；日期格式同 #30"),
54:("declared war on Japan. We must defeat Japan and","對日本宣戰。我們必須擊敗日本，",""),
55:("liberate the people of Asia!","解放亞洲人民！",""),
56:("After grueling battles, the Gibraltar of the Far","經過慘烈的戰鬥，遠東的","移除開頭雜訊「O」"),
57:("East, Singapore, finally fell into the hands of","直布羅陀——新加坡，終於落入",""),
58:("the Japanese. British Lt. Gen. Percival and Jap-","日軍手中。英軍中將白思華與日","Percival 譯為白思華；句尾 Jap- 為斷字"),
59:("anese Lt. Gen. Yamashita entered negotiations.","軍中將山下奉文展開談判。",""),
60:("General, I have a question for you. Are you","將軍，我有一個問題。您是否","移除開頭雜訊「5」"),
61:("aware that we are requesting your surrender?","知道，我們正要求您投降？",""),
62:("Your unconditional surrender, that is.","是無條件投降。",""),
63:("Yes, but no reason to be hasty, old man. I'd","是的，但何必這麼急呢，老兄。","移除開頭雜訊「5U」"),
64:("like to see the terms you're offering first.","我想先聽聽你們開出的條件。",""),
65:("I'm not offering any terms! Now listen. I am","沒有任何條件可談！聽清楚了，",""),
66:("asking for your unconditional surrender.","我要求的是你們無條件投降。",""),
67:("As I said, I will agree to your cease-fire. But","我說過，我同意停火。",""),
68:("only if I am satisfied with your terms.","但前提是我滿意你們的條件。",""),
69:("Mr. Percival! It's a simple yes or no question!","白思華先生！這只是是或否的問題！","移除開頭雜訊「H」"),
70:("As head of the British forces in this area, will","身為此地英軍的最高指揮官，",""),
71:("you surrender unconditionally?!","你是否無條件投降？！",""),
72:("Yes. I surrender..., unconditionally.","是。我投降……無條件投降。",""),
73:("The Prince of Wales would be sinking in a matter","威爾斯親王號沉沒只是",""),
74:("of time. As the crew prepared to abandon ship,","時間問題。當乘員準備棄艦時，",""),
75:("her commander, Sir Thomas Phillips of the","艦長——英國皇家海軍的",""),
76:("British Royal Navy, refused to leave his post.","湯姆·菲利普斯爵士拒絕離開崗位。",""),
77:("Commander, please! The Royal Navy cannot afford","艦長，請您務必離開！皇家海軍",""),
78:("to lose you! You must let her go!","不能失去您！您必須放手讓她走！",""),
79:("His staff pleaded with him frantically. But","幕僚們拼命懇求他。然而","移除開頭雜訊「1」"),
80:("Admiral Phillips smiled and quietly uttered","菲利普斯將軍微微一笑，平靜地",""),
81:("three words.","說出三個字。",""),
82:("No thank you.","不了，謝謝。","移除開頭雜訊「u>」；原文故意以三個字回絕"),
83:("Late that night, England's Prime Minister, W.S.","當天深夜，英國首相W.S.","移除開頭雜訊「P」"),
84:("Churchill, was pulled from his sleep by the sound","邱吉爾被床邊電話的鈴聲",""),
85:("of the telephone next to his bed. The voice over","從睡夢中驚醒。電話那頭的",""),
86:("the phone was strained.","聲音十分緊繃。",""),
87:("I'm terribly sorry to call you so late, sir. I","很抱歉這麼晚打擾您，首相。","移除開頭雜訊「9」"),
88:("have a report. The Prince of Wales and the","我有要事報告。威爾斯親王號與",""),
89:("Repulse were sunk in battle. We also lost Tom","反擊號在戰鬥中沉沒。湯姆·",""),
90:("Phillips.","菲利普斯也殉職了。",""),
91:("Are you certain of this, man?","你確定這消息屬實嗎？",""),
92:("","","二進位雜訊，無實際英文文字，跳過翻譯（待複核）"),
93:("It's been confirmed, sir.","已確認無誤，首相。",""),
94:("I see... Thank you for calling.","我知道了……謝謝你來電。","移除開頭雜訊「)」"),
95:("Anti-Japanese sentiment is growing in","反日情緒在",""),
96:("%s. As a result, the base there","%s日益高漲。當地基地",""),
97:("incurred damages.","因此蒙受損失。",""),
98:("People in %s have been holding peace","%s民眾發起和平",""),
99:("demonstrations. As a result, the base there","示威遊行。當地基地",""),
100:("sustained damages.","因此蒙受損失。",""),
101:("I have a report from the %s Intelligence ","%s情報部門","原文句尾空格為拼接用途，中譯省略"),
102:("Department. We succeeded in decoding the ","傳來報告。我們成功破譯了",""),
103:("%s cryptogram!","%s的密碼電文！",""),
104:("Germany now rules the Atlantic Ocean! We must","德國已稱霸大西洋！我們必須",""),
105:("seek out new territories - to the Pacific!","尋找新的領土——向太平洋進軍！",""),
106:("It is time for Germany to show all of Europe,","是時候讓德國向全歐洲——",""),
107:("no, the whole world its unstoppable power.","不，向全世界展示其無可阻擋的力量。",""),
108:("The Germans have conquered several areas of","德軍已征服歐洲",""),
109:("Europe and continue to take the offensive in","多個地區，並在數條",""),
110:("several lines of battle.","戰線上持續發動攻勢。",""),
111:("The Motherland will never fall! Final victory","祖國永不陷落！最終勝利",""),
112:("will be mine! I will not tolerate the idea of","必屬於我！我絕不容許",""),
113:("losing ground to the Allied dogs!","向盟軍走狗喪失一寸土地！",""),
114:("German forces are outnumbered throughout Europe.","德軍在歐洲各地兵力居於劣勢。",""),
115:("British and Soviet forces are gathering power in","英軍與蘇軍正在遠東",""),
116:("the Far East.","集結力量。",""),
117:("\"Now is the time for independence! People of","\"獨立的時刻到了！越南","移除開頭雜訊「)tc」；保留開頭引號（原文無收尾引號）"),
118:("Vietnam! Let us work as one to liberate our-","人民啊！讓我們團結一心，解放","our- 為斷字"),
119:("selves from imperialism!","自己，擺脫帝國主義！",""),
120:("Ho Chi Minh has organized an uprising against","胡志明在多個地區","移除開頭雜訊「A」"),
121:("the French in several areas. The ","組織了反抗法國的起義。",""),
122:("base at %s","%s基地",""),
123:(" was heavily bombarded and","遭到猛烈砲擊，","移除開頭雜訊「C7」"),
124:("the base facilities have incurred heavy damages.","基地設施損失慘重。",""),
125:("MacArthur has promised us freedom and","麥克阿瑟許諾給我們自由與",""),
126:("independence, but we, as Filipinos, must strive","獨立，但身為菲律賓人，",""),
127:("to free ourselves! Let us rise up against our","我們必須靠自己爭取解放！",""),
128:("Japanese oppressors!","起來反抗日本壓迫者吧！",""),
129:("Rising to President Keson's calling, the Filipi-","響應奎松總統的號召，菲律","Keson 應為 Quezon（奎松）之日式拼法；Filipi- 為斷字"),
130:("nos are engaging in anti-Japanese guerrilla war-","賓人展開抗日游擊戰。",""),
131:("fare. It appears the Japanese forces stationed","據報，駐紮在",""),
132:("at %s %s have suffered severe damage.","%s%s的日軍遭受重創。",""),
133:("Rising to President Keson's calling, the Fili-","響應奎松總統的號召，菲律","Fili- 為斷字"),
134:("pinos are engaging in anti-Japanese guerrilla","賓人展開抗日游擊",""),
135:("warfare. It appears the Japanese %s at","戰。據報，日軍%s（位於","為維持 %s 順序，以括號處理，待複核"),
136:("%s has suffered damages.","%s）遭受損失。",""),
137:("Report from the ","來自",""),
138:("B1%s %s %s","B1%s %s %s","B1 為遊戲控制碼，保留原樣"),
139:("\"Commencing attack on ","的報告：\"開始攻擊",""),
140:("Message from the ","來自",""),
141:("B1%s %s Fleet A.F.","B1%s %s艦隊航空隊","A.F. = Air Force，譯為航空隊"),
142:("\"Commencing attack on ","的電文：\"開始攻擊",""),
143:("Message from the ","來自","移除開頭雜訊「k」"),
144:("B1%s %s Fleet A.F.","B1%s %s艦隊航空隊",""),
145:("\"Engaged in battle with the ","的電文：\"正與",""),
146:("B1%s %s Fleet A.F.","B1%s %s艦隊航空隊交戰中",""),
147:("Message from the ","來自",""),
148:("B1%s %s Fleet A.F.","B1%s %s艦隊航空隊",""),
149:("\"Engaged in battle with the ","的電文：\"正與",""),
150:("B1%s %s Base A.F.","B1%s %s基地航空隊交戰中",""),
151:("Message from the ","來自",""),
152:("B1%s %s Fleet A.F.","B1%s %s艦隊航空隊",""),
153:("\"Commencing attack on ","的電文：\"開始攻擊",""),
154:("B1%s %s Base","B1%s %s基地",""),
155:("Message from the ","來自",""),
156:("B1%s %s Base A.F.","B1%s %s基地航空隊",""),
157:("\"Commencing attack on ","的電文：\"開始攻擊",""),
158:("Message from the ","來自",""),
159:("B1%s %s Base A.F.","B1%s %s基地航空隊",""),
160:("\"Engaged in battle with the ","的電文：\"正與",""),
161:("B1%s %s Fleet A.F.","B1%s %s艦隊航空隊交戰中",""),
162:("Message from the ","來自",""),
163:("B1%s %s Base A.F.","B1%s %s基地航空隊",""),
164:("\"Engaged in battle with the ","的電文：\"正與",""),
165:("B1%s %s Base A.F.","B1%s %s基地航空隊交戰中",""),
166:("Message from the ","來自","移除開頭雜訊「E」"),
167:("B1%s %s Base A.F.","B1%s %s基地航空隊",""),
168:("\"Commencing attack on ","的電文：\"開始攻擊",""),
169:("B1%s %s Base","B1%s %s基地",""),
170:("Red alert from the ","緊急警報——",""),
171:("B1%s %s %s","B1%s %s %s",""),
172:("B1%s %s ","B1%s %s",""),
173:("B1is approaching our unit.\"","B1正逼近我方部隊。\"",""),
174:("Red alert from the ","緊急警報——","移除開頭雜訊「'_@」"),
175:("B1%s %s Fleet A.F.","B1%s %s艦隊航空隊",""),
176:("B1%s A.F. ","B1%s航空隊",""),
177:("B1is approaching our unit.\"","B1正逼近我方部隊。\"",""),
178:("Red alert from the ","緊急警報——",""),
179:("B1%s %s Base A.F.","B1%s %s基地航空隊",""),
180:("B1%s A.F. ","B1%s航空隊",""),
181:("B1is approaching our unit.\"","B1正逼近我方部隊。\"",""),
182:("Red alert from the ","緊急警報——","移除開頭雜訊「S」"),
183:("B1%s %s Base","B1%s %s基地",""),
184:("B1%s A.F. ","B1%s航空隊",""),
185:("B1is approaching us.\"","B1正逼近我方。\"",""),
186:("","","二進位雜訊，無實際英文文字，跳過翻譯（待複核）"),
187:("Red alert from the ","緊急警報——","移除開頭雜訊「#」"),
188:("\"Our forces were destroyed!\"","\"我軍已被全滅！\"",""),
189:("Report from the ","來自",""),
190:("\"Our forces destroyed the ","的報告：\"我軍已擊滅敵方",""),
191:("Report from the ","來自",""),
192:("\"The battle with the ","的報告：\"與敵方",""),
193:("B1%s %s ","B1%s %s",""),
194:("B1reduced our force to %3d.\"","B1的戰鬥，使我方兵力降至%3d。\"",""),
195:("Red alert from the ","緊急警報——","移除開頭雜訊「G*&」"),
196:("B1%s Fleet A.F.","B1%s艦隊航空隊的通報",""),
197:("\"Our forces were destroyed!\"","\"我軍已被全滅！\"",""),
198:("Message from the ","來自","移除開頭雜訊「\\」"),
199:("B1%s Fleet A.F.","B1%s艦隊航空隊",""),
200:("\"Our forces destroyed the ","的電文：\"我軍已擊滅敵方",""),
201:("Message from the ","來自","移除開頭雜訊「w0」"),
202:("B1%s Fleet A.F.","B1%s艦隊航空隊",""),
203:("\"The battle with the ","的電文：\"與敵方",""),
204:("B1%s %s ","B1%s %s",""),
205:("B1reduced our aircrafts to %3d.\"","B1的戰鬥，使我方飛機降至%3d架。\"",""),
206:("Message from the ","來自",""),
207:("B1%s Fleet A.F.","B1%s艦隊航空隊",""),
208:("\"Air raid on the ","的電文：\"對敵方",""),
209:("B1%s %s Base ","B1%s %s基地",""),
210:("B1was successful!\"","B1的空襲成功！\"",""),
211:("Red alert from the ","緊急警報——",""),
212:("B1%s Base A.F.","B1%s基地航空隊的通報",""),
213:("\"Our forces were destroyed!\"","\"我軍已被全滅！\"",""),
214:("Message from the ","來自",""),
215:("B1%s Base A.F.","B1%s基地航空隊",""),
216:("\"Our forces destroyed the ","的電文：\"我軍已擊滅敵方",""),
217:("Message from the ","來自",""),
218:("B1%s Base A.F.","B1%s基地航空隊",""),
219:("\"The battle with the ","的電文：\"與敵方",""),
220:("B1%s %s ","B1%s %s",""),
221:("B1reduced our aircrafts to %3d.\"","B1的戰鬥，使我方飛機降至%3d架。\"",""),
222:("Message from the ","來自",""),
223:("B1%s Base A.F.","B1%s基地航空隊",""),
224:("\"Air raid on the ","的電文：\"對敵方",""),
225:("B1%s %s Base ","B1%s %s基地",""),
226:("B1was successful!.\"","B1的空襲成功！\"","原文句尾標點「!.」疑似筆誤"),
227:("Red alert from the ","緊急警報——","移除開頭雜訊「K」"),
228:("B1%s Base","B1%s基地的通報",""),
229:("\"Severe damage incurred from the ","\"遭受敵方",""),
230:("B1%s Air Force's ","B1%s空軍",""),
231:("B1raid.\"","B1的空襲，損失嚴重。\"",""),
232:("Red alert from the ","緊急警報——",""),
233:("\"The armory of the ","的通報：\"","armory 在此指艦上彈藥庫，譯文移至 #235"),
234:("C%d%s %s ","C%d%s %s","C 為遊戲控制碼，保留原樣"),
235:("caught fire and sunk!\"","的彈藥庫起火，艦體沉沒！\"",""),
236:("Red alert from the ","緊急警報——",""),
237:("C7submarine.","C7潛艇。","C7 為遊戲控制碼，保留原樣"),
238:("\"Armor damaged by enemy fire.","通報：\"裝甲遭敵火擊破。",""),
239:("Sub explodes under pressure.\"","潛艇因水壓爆炸。\"",""),
240:("Report from the %s. ","來自%s的報告。",""),
241:("Sunk due to lack of materials.","因物資耗盡而沉沒。",""),
242:("Report from the %s submarine. ","來自%s潛艇的報告。",""),
243:("Sunk due to lack of materials.","因物資耗盡而沉沒。",""),
244:("Report from the %s. Remaining materials scarce. Request aid.","來自%s的報告。剩餘物資稀少，請求補給。","移除開頭雜訊「3」"),
245:("Report from the %s submarine. Remaining materials scarce. Request aid.","來自%s潛艇的報告。剩餘物資稀少，請求補給。",""),
246:("Report from the %s submarine. Sunk by enemy's escort ship when attacking the %s %s Base transports.","來自%s潛艇的報告。攻擊%s%s基地運輸船時，遭敵方護衛艦擊沉。",""),
247:("Report from the %s %s Base. Detected and sunk enemy submarine.","來自%s%s基地的報告。發現並擊沉敵方潛艇。",""),
248:("Germany takes Moscow. Germany and the USSR sign","德國攻佔莫斯科。德國與蘇聯簽署",""),
249:("a peace fire agreement.","停火協議。","原文 peace fire 應為 cease-fire（停火）之誤"),
250:("Germany puts its \"Ashika Operation\" into action.","德國將\"海獅作戰\"付諸行動。","Ashika（あしか）即海獅，推定為海獅作戰（Operation Sea Lion），待複核"),
251:("England takes heavy losses at home. Prime","英國本土遭受重創。首相",""),
252:("Minister Churchill begins talks with Germany","邱吉爾開始與德國",""),
253:("about terms for peace.","商談和平條件。",""),
254:("The Third Reich unites Europe under its","第三帝國將歐洲置於其統治之下。","移除開頭雜訊「K」；原文句尾不完整（under its…），譯文補足語意，待複核"),
255:("\"The German capital of Berlin falls. Adolph","\"德國首都柏林陷落。阿道夫·","移除開頭雜訊「|-q/」；保留開頭引號"),
256:("Hitler commits suicide, and the new Communist","希特勒自殺身亡，德國新的",""),
257:("government of Germany looks to the Allies for","共產政府轉而尋求與盟軍",""),
258:("negotiations for peace.","進行和平談判。",""),
259:("The war in Europe is finally over!","歐洲戰事終於結束了！",""),
260:("","","二進位雜訊，無實際英文文字，跳過翻譯（待複核）"),
261:("","","二進位雜訊，無實際英文文字，跳過翻譯（待複核）"),
}

PH = re.compile(r"%\d*[sd]")

def main():
    with open(SRC, newline="", encoding="utf-8-sig") as f:
        rows = list(csv.DictReader(f, escapechar="\\"))
    assert len(rows) == len(M), f"row count {len(rows)} != mapping {len(M)}"

    errors = []
    out = []
    for r in rows:
        num = int(r["id"].rsplit(":", 1)[1])
        cleaned, target, note = M[num]
        src = r["source"]
        if cleaned:
            # cleaning must only strip a short prefix
            if not src.endswith(cleaned):
                errors.append(f"{r['id']}: cleaned text is not a suffix of source: {src!r} -> {cleaned!r}")
            elif len(src) - len(cleaned) > 6:
                errors.append(f"{r['id']}: stripped prefix too long ({len(src)-len(cleaned)} chars)")
            # placeholder multiset must match between cleaned source and target
            if sorted(PH.findall(cleaned)) != sorted(PH.findall(target)):
                errors.append(f"{r['id']}: placeholder mismatch {PH.findall(cleaned)} vs {PH.findall(target)}")
            # ASCII double-quote count must match
            if cleaned.count('"') != target.count('"'):
                errors.append(f"{r['id']}: quote count mismatch")
        out.append({"file": r["file"], "id": r["id"], "offset": r["offset"],
                    "source": cleaned, "target": target, "note": note})
    if errors:
        print("\n".join(errors)); sys.exit(1)

    with open(DST, "w", newline="", encoding="utf-8-sig") as f:
        w = csv.DictWriter(f, fieldnames=["file","id","offset","source","target","note"],
                           quoting=csv.QUOTE_ALL, escapechar="\\", lineterminator="\r\n")
        w.writeheader()
        w.writerows(out)
    print(f"wrote {DST}: {len(out)} rows")

if __name__ == "__main__":
    main()
